---
- name: creation and pushing of docker image
  hosts: jenkins
  become: yes
  tasks:
    - name: update apt package casche
      apt:
        update_cache: yes
    - name: build docker image
      command: docker build -t image1 .
      args:
        chdir: /var/lib/jenkins/workspace/sample-pipeline
    - name: tage image
      command: docker tag image1:latest aarizsak/image1:latest
    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: aarizsak
        password: dckr_pat_Y2ioXpoA0jybHrgFbP-xChCj-Rc


    - name: Push image
      command: docker push aarizsak/image1:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 aarizsak/image1:latest
